
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name:  non-prod-cluster
  region: ap-south-1
  version: "1.28"

vpc:
## Make sure that this CIDR doesn't overlaps with any other exisiting VPC with which a peering needs to be done.
  cidr: "10.0.0.0/16"

nodeGroups:
  - name: non-prod-nodes
    availabilityZones:
      - ap-south-1a
    privateNetworking: true
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    instancesDistribution:
      instanceTypes: ["m7a.xlarge	"]
      onDemandBaseCapacity: 0
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
    ssh:
      allow: true
      publicKeyName: "xxxxxx"
    volumeSize: 500
    kubeletExtraConfig:
        kubeReserved:
            cpu: "200m"
            memory: "200Mi"
            ephemeral-storage: "1Gi"
        kubeReservedCgroup: "/kube-reserved"
        cpuManagerPolicy: "static"
        systemReserved:
            cpu: "200m"
            memory: "200Mi"
            ephemeral-storage: "1Gi"
        evictionHard:
            memory.available:  "200Mi"
            nodefs.available: "10%"
        featureGates:
            RotateKubeletServerCertificate: true
            CPUManager: true
